#!/usr/bin/env node
/**
 * Writes prisma/schema.postgres.prisma: the same data model as prisma/schema.prisma (SQLite, used
 * for local development) with a PostgreSQL datasource, for production builds (`npm run vercel-build`).
 * When DATABASE_URL_UNPOOLED is set (Neon on Vercel), schema changes use that direct connection
 * while the app uses the pooled DATABASE_URL.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const prismaDir = resolve(dirname(fileURLToPath(import.meta.url)), '../prisma');
const source = readFileSync(resolve(prismaDir, 'schema.prisma'), 'utf8');

const DATASOURCE = /datasource\s+db\s*\{[^}]*\}/;
if (!DATASOURCE.test(source)) throw new Error('prisma/schema.prisma has no `datasource db { ... }` block');

const datasource = [
  'datasource db {',
  '  provider  = "postgresql"',
  '  url       = env("DATABASE_URL")',
  ...(process.env.DATABASE_URL_UNPOOLED ? ['  directUrl = env("DATABASE_URL_UNPOOLED")'] : []),
  '}',
].join('\n');

const header = '// GENERATED by scripts/postgres-schema.mjs from schema.prisma - edit schema.prisma instead.\n\n';
writeFileSync(resolve(prismaDir, 'schema.postgres.prisma'), header + source.replace(DATASOURCE, datasource));
console.log(
  `✔ Wrote prisma/schema.postgres.prisma (PostgreSQL${process.env.DATABASE_URL_UNPOOLED ? ', direct connection for schema changes' : ''})`,
);
